# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cafe_crawler.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 309)
        MainWindow.setStyleSheet("background-color: #282857;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("border-style: outset;\n"
"border-width: 0px;\n"
"border-color: black;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 3px;\n"
"padding-bottom: 3px;\n"
"color:#ffffff;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setStyleSheet("border-style: outset;\n"
"border-width: 0px;\n"
"border-color: black;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 3px;\n"
"padding-bottom: 3px;\n"
"color:#ffffff;")
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 2, 0, 1, 1)
        self.N_count = QtWidgets.QRadioButton(self.centralwidget)
        self.N_count.setStyleSheet("border-style: outset;\n"
"border-width: 0px;\n"
"border-color: black;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 3px;\n"
"padding-bottom: 3px;\n"
"color:#ffffff;")
        self.N_count.setObjectName("N_count")
        self.gridLayout.addWidget(self.N_count, 1, 0, 1, 1)
        self.excel_name = QtWidgets.QLabel(self.centralwidget)
        self.excel_name.setStyleSheet("border-style: outset;\n"
"border-width: 0px;\n"
"border-color: black;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 3px;\n"
"padding-bottom: 3px;\n"
"color:#ffffff;")
        self.excel_name.setObjectName("excel_name")
        self.gridLayout.addWidget(self.excel_name, 4, 0, 1, 1)
        self.form_N = QtWidgets.QLineEdit(self.centralwidget)
        self.form_N.setReadOnly(True)
        self.form_N.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 50px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"background-color: rgb(247, 247, 247);\n"
"padding-top: 3px;\n"
"padding-bottom: 3px;")
        self.form_N.setObjectName("form_N")
        self.gridLayout.addWidget(self.form_N, 1, 2, 1, 1)
        self.form_id = QtWidgets.QLineEdit(self.centralwidget)
        self.form_id.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 50px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"background-color: rgb(247, 247, 247);\n"
"padding-top: 3px;\n"
"padding-bottom: 3px;")
        self.form_id.setObjectName("form_id")
        self.gridLayout.addWidget(self.form_id, 2, 2, 1, 1)
        self.form_pw = QtWidgets.QLineEdit(self.centralwidget)
        self.form_pw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.form_pw.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 50px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"background-color: rgb(247, 247, 247);\n"
"padding-top: 3px;\n"
"padding-bottom: 3px;")
        self.form_pw.setObjectName("form_pw")
        self.gridLayout.addWidget(self.form_pw, 3, 2, 1, 1)
        self.form_excel_name = QtWidgets.QLineEdit(self.centralwidget)
        self.form_excel_name.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 50px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"background-color: rgb(247, 247, 247);\n"
"padding-top: 3px;\n"
"padding-bottom: 3px;")
        self.form_excel_name.setObjectName("form_excel_name")
        self.gridLayout.addWidget(self.form_excel_name, 4, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.today = QtWidgets.QRadioButton(self.centralwidget)
        self.today.setStyleSheet("border-style: outset;\n"
"border-width: 0px;\n"
"border-color: black;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 3px;\n"
"padding-bottom: 3px;\n"
"color:#ffffff;")
        self.today.setObjectName("today")
        self.gridLayout_2.addWidget(self.today, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"background-color: rgb(247, 247, 247);\n"
"padding-top: 3px;\n"
"padding-bottom: 3px;")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 2, 0, 1, 1)
        self.run = QtWidgets.QPushButton(self.centralwidget)
        self.run.setStyleSheet("padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 3px;\n"
"padding-bottom: 3px;\n"
"color:#ffffff;")
        self.run.setObjectName("run")
        self.gridLayout_2.addWidget(self.run, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "비밀번호"))
        self.password_label.setText(_translate("MainWindow", "아이디"))
        self.N_count.setText(_translate("MainWindow", "최근 N개 가져오기"))
        self.excel_name.setText(_translate("MainWindow", "엑셀파일명"))
        self.today.setText(_translate("MainWindow", "오늘 가입자 정보 가져오기"))
        self.run.setText(_translate("MainWindow", "실행"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
